### ISSUE TITLE
Allow use of 24-Hours-style for timestamps

### ISSUE THREAD

**Issue by FF-11** [wikimedia-gadgets/twinkle-core#11]
In many languages, timestamps are always formated in 24-hour-style, for example:
9:00 instead of 9:00 AM and 21:00 instead of 9:00 PM.

Please:

* [x] Add support for this
* [ ] Inform about how to use the 24-hour-style in the _translatewiki.net_ message documentation.

Messages that should support 24-hour timestamps include:
[this](https://translatewiki.net/w/i.php?title=Special:Translate&showMessage=twinkle-relative-today&group=twinkle-core&language=de&filter=&optional=1&action=translate), [this](https://translatewiki.net/w/i.php?title=Special:Translate&showMessage=twinkle-relative-prevday&group=twinkle-core&language=de&filter=&optional=1&action=translate) and [this](https://translatewiki.net/w/i.php?title=Special:Translate&showMessage=twinkle-relative-pastweek&group=twinkle-core&language=de&filter=&optional=1&action=translate)

If it's already supported, you just need to inform about it

Thank you!

**Comment by Xi-Plus** [comment]
@FF-11 `hh` for 12-hours, `HH` for 24-hours. You can find the rules [here](https://github.com/wikimedia-gadgets/twinkle-core/blob/eb2ab3e84391f6680cba2b3b8503885f06188411/morebits/morebits.js#L1993).

**Comment by siddharthvp** [comment]
The syntax reference is only available in the rendered documentation [here](http://wikimedia-gadgets.github.io/twinkle/Morebits.date.html#format). I've updated the message documentations to point to it. Thanks for raising this issue!
